  // laptop db
export const laptops = [
  // Initial 29 Laptops
  { id: 1, name: "Dell XPS 13 (2024)", brand: "Dell", price: 1299, cpu: "i7", gpu: "Integrated" },
  { id: 2, name: "MacBook Air M3", brand: "Apple", price: 1099, cpu: "M3", gpu: "Integrated"},
  { id: 3, name: "HP Spectre x360", brand: "HP", price: 1499, cpu: "i7", gpu: "Integrated"},
  { id: 4, name: "Lenovo Legion 5", brand: "Lenovo", price: 1199, cpu: "i5", gpu: "RTX 4060"},
  { id: 5, name: "Asus ROG Zephyrus G16", brand: "Asus", price: 1999, cpu: "R9", gpu: "RTX 4080"},
  { id: 6, name: "Dell G15 Gaming", brand: "Dell", price: 950, cpu: "i5", gpu: "RTX 3050"},
  { id: 7, name: "Apple MacBook Pro 14", brand: "Apple", price: 2199, cpu: "M3 Pro", gpu: "M3 Pro"},
  { id: 8, name: "Lenovo ThinkPad X1", brand: "Lenovo", price: 1550, cpu: "i7", gpu: "Integrated"},
  { id: 9, name: "MSI Raider GE78", brand: "MSI", price: 2499, cpu: "i9", gpu: "RTX 4090"},
  // Added 20 new laptops
  { id: 10, name: "Acer Swift 5", brand: "Acer", price: 850, cpu: "i5", gpu: "Integrated"},
  { id: 11, name: "Microsoft Surface Laptop 5", brand: "Microsoft", price: 1350, cpu: "i7", gpu: "Integrated"},
  { id: 12, name: "Razer Blade 16", brand: "Razer", price: 2899, cpu: "i9", gpu: "RTX 4070"},
  { id: 13, name: "LG Gram 17", brand: "LG", price: 1100, cpu: "i5", gpu: "Integrated"},
  { id: 14, name: "Samsung Galaxy Book 4 Ultra", brand: "Samsung", price: 2300, cpu: "i9"},
  { id: 15, name: "Asus ZenBook Duo", brand: "Asus", price: 1700, cpu: "i7", gpu: "Integrated"},
  { id: 16, name: "Dell Precision 7780", brand: "Dell", price: 3500, cpu: "i9", gpu: "RTX 5000"},
  { id: 17, name: "HP Omen 16", brand: "HP", price: 1600, cpu: "R7", gpu: "RTX 4060"},
  { id: 18, name: "Lenovo IdeaPad Flex 5", brand: "Lenovo", price: 799, cpu: "R5", gpu: "Integrated"},
  { id: 19, name: "Apple MacBook Air M2 15\"", brand: "Apple", price: 1199, cpu: "M2", gpu: "Integrated"},
  { id: 20, name: "MSI Stealth 18", brand: "MSI", price: 2200, cpu: "i7", gpu: "RTX 4080"},
  { id: 21, name: "Acer Predator Helios 300", brand: "Acer", price: 1800, cpu: "i7", gpu: "RTX 4070" },
  { id: 22, name: "Microsoft Surface Pro 9", brand: "Microsoft", price: 1050, cpu: "i5", gpu: "Integrated"},
  { id: 23, name: "Razer Blade 14", brand: "Razer", price: 1999, cpu: "R9", gpu: "RTX 4060"},
  { id: 24, name: "LG Ultra PC", brand: "LG", price: 900, cpu: "R7", gpu: "Integrated"},
  { id: 25, name: "Samsung Galaxy Book 3 360", brand: "Samsung", price: 1450, cpu: "i7", gpu: "Integrated"},
  { id: 26, name: "Asus Vivobook 15", brand: "Asus", price: 650, cpu: "i5", gpu: "Integrated"},
  { id: 27, name: "Dell Latitude 5400", brand: "Dell", price: 980, cpu: "i5", gpu: "Integrated"},
  { id: 28, name: "HP Pavilion Aero 13", brand: "HP", price: 999, cpu: "R7", gpu: "Integrated"},
  { id: 29, name: "Lenovo ThinkBook 14", brand: "Lenovo", price: 1150, cpu: "i7", gpu: "Integrated"},
];